version: '3.7'
services:
  my-mongo-container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwordot
    volumes:
      - ./mongodb/data/db:/data/db
    ports:
      - '27017-27019:27017-27019'

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: passwordot
      ME_CONFIG_MONGODB_SERVER: my-mongo-container
